### ISSUE TITLE
"Load to editor" (Instance) not working

### ISSUE THREAD

**Issue by jodiw01** [lcnetdev/recto#23]
Steps to duplicate:

Search for LCCN 2018469658 in the BF db
Click "Load to editor" button
The software correctly invokes the "Load IBC" menu option, but the URL is not transferred

Selecting a profile to use (Monograph in this case), and click the "Submit URL" button produces an error message "Please choose an Instance to load". This is the correct response, but the Load to Editor function should transfer the URL in the same way it does when loading works.

**Comment by kefo** [comment]
Should be working.  Did for me now.  If good, please close.

**Comment by jodiw01** [comment]
I followed the above steps, but the URL only appears in the search box after I do a hard refresh. The Load to Editor function now opens the editor in a new tab and refreshing a newly-opened browser tab should not be necessary.

**Comment by jodiw01** [comment]
fixed
